# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ifree-sms}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Igor Galeta", "Pavlo Galeta"]
  s.date = %q{2011-05-30}
  s.description = %q{The IfreeSms gem for i-free sms provider}
  s.email = %q{superp1987@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "app/models/ifree_sms/message.rb",
    "lib/generators/ifree_sms/USAGE",
    "lib/generators/ifree_sms/install_generator.rb",
    "lib/generators/ifree_sms/templates/config/ifree_sms.rb",
    "lib/generators/ifree_sms/templates/migrate/create_messages.rb",
    "lib/ifree-sms.rb",
    "lib/ifree_sms.rb",
    "lib/ifree_sms/callbacks.rb",
    "lib/ifree_sms/config.rb",
    "lib/ifree_sms/engine.rb",
    "lib/ifree_sms/manager.rb",
    "lib/ifree_sms/smsing.rb",
    "lib/ifree_sms/version.rb"
  ]
  s.homepage = %q{https://github.com/superp/ifree-sms}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{The IfreeSms gem for i-free sms provider}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<curb>, ["~> 0.7.15"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4.4"])
      s.add_runtime_dependency(%q<activemodel>, [">= 0"])
    else
      s.add_dependency(%q<curb>, ["~> 0.7.15"])
      s.add_dependency(%q<nokogiri>, ["~> 1.4.4"])
      s.add_dependency(%q<activemodel>, [">= 0"])
    end
  else
    s.add_dependency(%q<curb>, ["~> 0.7.15"])
    s.add_dependency(%q<nokogiri>, ["~> 1.4.4"])
    s.add_dependency(%q<activemodel>, [">= 0"])
  end
end

